root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
# Array of commands to run before each build
pre_cmd = [
  "go run github.com/a-h/templ/cmd/templ@latest generate",
  "npm --prefix app run build",
]
cmd = "go build -o ./tmp/main cmd/nicklesseos.com/main.go"
delay = 0
exclude_dir = [
  "node_modules",
  "app/node_modules",
  "assets",
  "tmp",
  "vendor",
  "testdata",
]
exclude_file = []
exclude_regex = ["_test.go", "_templ.go", "bundle.js", "bundle.css"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = ["cmd", "src", "app", "models", "handlers"]
include_ext = ["go", "ts", "js", "html", "css", "templ"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
