// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/blackflame007/nicklesseos.com/app/components"

func header(isAuthenticated bool) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header class=\"bg-neutral p-5\"><div class=\"container mx-auto flex flex-wrap justify-between items-center\"><a class=\"text-primary font-bold text-xl\" href=\"/\">nicklesseos.com</a><nav><ul class=\"flex space-x-4\"><li><a href=\"/\" class=\"text-secondary hover:text-accent\">Home</a></li><li><a href=\"/about\" class=\"text-secondary hover:text-accent\">About</a></li><li><a href=\"/g\" class=\"text-secondary hover:text-accent\">Gallery</a></li><li><a href=\"/portfolio\" class=\"text-secondary hover:text-accent\">Portfolio</a></li></ul></nav><div class=\"container mx-auto flex flex-wrap justify-between items-center\"><button onclick=\"toggleTheme()\" class=\"btn btn-primary mt-3 sm:mt-0\">Toggle Theme</button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.AuthButton(isAuthenticated).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
