// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Hero Section --><section class=\"hero bg-base-100 text-neutral-content\"><div class=\"text-center hero-content\"><div class=\"max-w-xs sm:max-w-md\"><h1 class=\"mb-5 text-3xl sm:text-5xl font-bold\">Welcome to nicklesseos.com</h1><p class=\"mb-5\">Here's where code meets creativity. Take a peek into my world of innovative software solutions and tech explorations.</p><a href=\"/portfolio\"><button class=\"btn btn-primary\">Start Exploring</button></a></div></div></section><!-- About Section --><section class=\"py-12 bg-neutral text-neutral-content\"><div class=\"container mx-auto flex flex-col items-center\"><h2 class=\"text-4xl font-bold text-center mb-6\">About Nick</h2><p class=\"text-xl text-center pb-4\">Hi, I'm Nick Lesseos. A software engineer by trade, tech enthusiast by heart. From automating complex tasks to developing cutting-edge applications, I'm all about making things smarter and life easier.</p><a href=\"/about\"><button class=\"btn btn-primary\">Learn about me</button></a></div></section><!-- Contact Section --><section class=\"py-12 bg-base-100\"><div class=\"container mx-auto\"><h2 class=\"text-4xl font-bold text-center mb-6\">Let's Connect</h2><div class=\"flex justify-center\"><div class=\"card w-96 bg-neutral text-neutral-content\"><div class=\"card-body\"><p>Got a project in mind or want to discuss the latest in tech? I'm just an email or call away.</p><p>Email: info@nicklesseos.com</p><p>Phone: 123-456-7890</p></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
