name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      run: go test -v ./...

    - name: Build Docker Image SHA
      run: docker build -t blackflame007/nicklesseos.com:${{ github.sha }} .

    - name: Build Docker Image Latest
      run: docker build -t blackflame007/nicklesseos.com:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker SHA Image
      run: docker push blackflame007/nicklesseos.com:${{ github.sha }}

    - name: Push Docker Latest Image
      run: docker push blackflame007/nicklesseos.com:latest

    # Terraform Deployment
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform -chdir=terraform init -backend-config="access_key=${{ secrets.DO_SPACES_ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.DO_SPACES_SECRET_KEY }}" -backend-config="bucket=tfstate-echobase"

    - name: Terraform Plan
      run: terraform -chdir=terraform plan
      env:
        TF_VAR_do_token: ${{ secrets.DO_API_TOKEN }}
        TF_VAR_do_spaces_access_key: ${{ secrets.DO_SPACES_ACCESS_KEY }}
        TF_VAR_do_spaces_secret_key: ${{ secrets.DO_SPACES_SECRET_KEY }}
        TF_VAR_docker_image: blackflame007/nicklesseos.com:latest
        TF_VAR_ssh_fingerprint: ${{ secrets.KEYPAIR_FP_PUB }}
        TF_VAR_pvt_key: ${{ secrets.KEYPAIR_PRIVATE }}

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve
      env:
        TF_VAR_do_api_token: ${{ secrets.DO_API_TOKEN }}
        TF_VAR_do_spaces_access_key: ${{ secrets.DO_SPACES_ACCESS_KEY }}
        TF_VAR_do_spaces_secret_key: ${{ secrets.DO_SPACES_SECRET_KEY }}
        TF_VAR_docker_image: blackflame007/nicklesseos.com:latest
        TF_VAR_ssh_fingerprint: ${{ secrets.KEYPAIR_FP_PUB }}
        TF_VAR_pvt_key: ${{ secrets.KEYPAIR_PRIVATE }}
